### ISSUE TITLE
🔋 percentage

### ISSUE THREAD

**Issue by rolfie23** [FilipDem/Domoticz-iROBOT-ROOMBA-plugin#3]
Hello,

Had a lot of problems today with the roomba. 🔋 was dead.

Is there an possibility to have an device for the accu? Then I can make some actions with it.

Rolf

**Comment by FilipDem** [comment]
Hi Rolf,

The battery is updated in one of the two devices. Don't know exactly which
one by heart. You can see it if you go to the Devices window.

If you you set the notifications, you will normally be updated if the
battery goes below a certain level... Don't know exactly anymore.

I had the same while ago. The Roomba was not set correctly on his base...
And was warned by mail... So it works.

Is this enough (as this is standard Domoticz) or do you really want a
dedicated extra device?

Thanks

F

Op za 12 jun. 2021 22:25 schreef rolfie23 ***@***.***>:

**Comment by rolfie23** [comment]
I know it's there, for scripts I want a dedicated device. Also the accu percentage isn't logged there.

**Comment by FilipDem** [comment]
The accu percentage is logged. However no problem. Next weekend I make you
a dedicated device with the battery percentage.

Let you know once done.

Filip

Op zo 13 jun. 2021 15:00 schreef rolfie23 ***@***.***>:

**Comment by FilipDem** [comment]
Hi Rolf,
I just committed the change to get the additional "battery" device. See also the readme... The device is not visible by default. You need to make it visible in the menu Settings - Devices. Search for the "roomba"-devices and click the "Add Device" icon (should be a small green right arrow icon).
Let me know your feedback so that we can close the issue.

**Comment by rolfie23** [comment]
![Screenshot_20210622-085450-750](https://user-images.githubusercontent.com/61058985/122878152-b055b100-d337-11eb-870d-6b4da139fd96.png)
Thanks! Acting a little trange (drops of 10% an long time after working stays on 80%) but can work with it!
